# Generated by Django 3.2.15 on 2022-12-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="color",
            field=models.CharField(default="#800020", max_length=50),
        ),
    ]
