# Generated by Django 3.2.15 on 2023-01-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
