# Generated by Django 3.2.15 on 2023-02-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_auto_20230111_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_account',
            field=models.BooleanField(default=True),
        ),
    ]
