# Generated by Django 3.2.15 on 2023-02-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_user_booking_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
