# Generated by Django 3.2.15 on 2023-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0008_user_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='booking_profile',
            field=models.BooleanField(default=True),
        ),
    ]
