# Generated by Django 3.2.15 on 2023-02-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0009_userprofile_booking_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
