from django.contrib import admin
from .models import *

admin.site.register(Banners)
admin.site.register(Company)
admin.site.register(Tax)
admin.site.register(Service)
admin.site.register(Package)
admin.site.register(Item)
admin.site.register(Extra)
admin.site.register(Booking)
admin.site.register(BookingOrderDetails)
admin.site.register(BookingExtraDetails)
admin.site.register(BookingItemDetails)
admin.site.register(BODItemDetails)
admin.site.register(BODServiceLocation)
admin.site.register(BODExtraDetails)
admin.site.register(BODContactInfo)
admin.site.register(Schedule)
admin.site.register(Sale)
admin.site.register(PaymentSale)
admin.site.register(Frequency)
admin.site.register(ServiceLocation)
admin.site.register(BookingProblem)
admin.site.register(BookingAttachments)
admin.site.register(DispatchedAppointment)
admin.site.register(CustomerSupportCollection)
admin.site.register(CustomerSupportChat)
admin.site.register(UserStripe)
admin.site.register(EmailLogs)
admin.site.register(BookingNotifications)
admin.site.register(Invoice)
admin.site.register(Payroll)
admin.site.register(EmailTypes)
admin.site.register(PayrollLedger)
admin.site.register(PageViewsCount)
