# Generated by Django 3.2.15 on 2022-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetime",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
