# Generated by Django 3.2.15 on 2022-10-25 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "booking",
            "0004_bodcontactinfo_bodservicelocation_booking_bookingorderdetails_frequency_servicelocation",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingExtraDetailsAbstract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.extra"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingItemDetailsAbstract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bod", models.CharField(default="0", max_length=148)),
                ("user", models.CharField(default="null", max_length=250)),
                ("stripe_customer", models.CharField(max_length=148)),
            ],
        ),
        migrations.AlterField(
            model_name="frequency",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Dispatched", "Dispatched"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=24,
                    ),
                ),
                ("shift_started", models.BooleanField(default=False)),
                ("colour", models.CharField(default="#FFA500", max_length=124)),
                ("shift_ended", models.BooleanField(default=False)),
                ("tip_amount", models.FloatField(default=0.0)),
                (
                    "shift_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("on_progress", "on_progress"),
                            ("completed", "completed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_in_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("paid", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("partial", "partial"),
                            ("completed", "completed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(default="card", max_length=48)),
                ("capture", models.CharField(max_length=48, null=True)),
                ("amount", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingItemDetails",
            fields=[
                (
                    "bookingitemdetailsabstract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking.bookingitemdetailsabstract",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                    ),
                ),
            ],
            bases=("booking.bookingitemdetailsabstract",),
        ),
        migrations.CreateModel(
            name="BookingExtraDetails",
            fields=[
                (
                    "bookingextradetailsabstract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking.bookingextradetailsabstract",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                    ),
                ),
            ],
            bases=("booking.bookingextradetailsabstract",),
        ),
        migrations.CreateModel(
            name="BODItemDetails",
            fields=[
                (
                    "bookingitemdetailsabstract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking.bookingitemdetailsabstract",
                    ),
                ),
                (
                    "bod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.bookingorderdetails",
                    ),
                ),
            ],
            bases=("booking.bookingitemdetailsabstract",),
        ),
        migrations.CreateModel(
            name="BODExtraDetails",
            fields=[
                (
                    "bookingextradetailsabstract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking.bookingextradetailsabstract",
                    ),
                ),
                (
                    "bod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.bookingorderdetails",
                    ),
                ),
            ],
            bases=("booking.bookingextradetailsabstract",),
        ),
    ]
