# Generated by Django 3.2.15 on 2022-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_auto_20221025_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frequency",
            name="start_date",
            field=models.DateField(),
        ),
    ]
