# Generated by Django 3.2.15 on 2022-10-25 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0006_alter_frequency_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_in_schedule",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
