# Generated by Django 3.2.15 on 2022-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_schedule_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripeid",
            name="user",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
