# Generated by Django 3.2.15 on 2022-11-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_auto_20221113_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_in_schedule",
                to="booking.booking",
            ),
        ),
    ]
