# Generated by Django 3.2.15 on 2022-11-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_stripeid_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsale",
            name="capture",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
