# Generated by Django 3.2.15 on 2022-11-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0014_alter_paymentsale_capture"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchedAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Dispatched", "Dispatched"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Dispatched",
                        max_length=24,
                    ),
                ),
                ("shift_started", models.BooleanField(default=False)),
                ("shift_ended", models.BooleanField(default=False)),
                (
                    "shift_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("on_progress", "on_progress"),
                            ("completed", "completed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_in_dispatched_appointment",
                        to="booking.schedule",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_in_dispatched_appointment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
