# Generated by Django 3.2.15 on 2022-11-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_dispatchedappointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchedappointment",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="dispatchedappointment",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="dispatchedappointment",
            name="start_time",
        ),
        migrations.AddField(
            model_name="dispatchedappointment",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_in_dispatched_appointment",
                to="booking.booking",
            ),
        ),
    ]
