# Generated by Django 3.2.15 on 2022-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_customersupportchat_customersupportcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsale",
            name="is_captured",
            field=models.BooleanField(default=True),
        ),
    ]
