# Generated by Django 3.2.15 on 2022-12-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_bookingnotifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchedappointment",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_in_dispatched_appointment",
                to="booking.booking",
            ),
        ),
    ]
