# Generated by Django 3.2.15 on 2022-12-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_alter_dispatchedappointment_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customersupportchat",
            name="user",
        ),
    ]
