# Generated by Django 3.2.15 on 2022-12-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0024_remove_customersupportchat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersupportchat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_in_customer_support",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
