# Generated by Django 3.2.15 on 2022-12-18 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0025_customersupportchat_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hourly_wage", models.FloatField(default=0.0)),
                ("total_hours", models.FloatField(default=0.0)),
                ("total_amount", models.FloatField(default=0.0)),
                ("tip_amount", models.FloatField(default=0.0)),
                ("paid_amount", models.FloatField(default=0.0)),
                ("due_amount", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_provider_in_payroll",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                            ("Due", "Due"),
                        ],
                        default="Due",
                        max_length=30,
                    ),
                ),
                ("hourly_wage", models.FloatField(default=0.0)),
                ("total_hours", models.FloatField(default=0.0)),
                ("total_amount", models.FloatField(default=0.0)),
                ("tip_amount", models.FloatField(default=0.0)),
                ("paid_amount", models.FloatField(default=0.0)),
                ("due_amount", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.schedule",
                    ),
                ),
                (
                    "sp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_provider_in_invoice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
