# Generated by Django 3.2.15 on 2022-12-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0026_invoice_payroll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingnotifications",
            name="booking",
        ),
        migrations.AddField(
            model_name="bookingnotifications",
            name="bod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.bookingorderdetails",
            ),
        ),
    ]
