# Generated by Django 3.2.15 on 2022-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0028_auto_20221220_1843"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="one_day_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="three_day_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="three_hour_reminder",
            field=models.BooleanField(default=False),
        ),
    ]
