# Generated by Django 3.2.15 on 2022-12-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0029_auto_20221221_1409"),
    ]

    operations = []
