# Generated by Django 3.2.15 on 2022-12-24 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20221222_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_in_payroll', to='booking.booking'),
        ),
    ]
