# Generated by Django 3.2.15 on 2022-12-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_payroll_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportcollection',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
