# Generated by Django 3.2.15 on 2022-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_chargetip_userinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
