# Generated by Django 3.2.15 on 2023-01-21 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0040_remove_customersupportchat_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('payroll', models.ManyToManyField(related_name='payroll_in_payroll_ledger', to='booking.Payroll')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_in_payroll_ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
