# Generated by Django 3.2.15 on 2023-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_bookingnotifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.CharField(default='null', max_length=124),
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.CharField(default='null', max_length=124),
        ),
    ]
