# Generated by Django 3.2.15 on 2023-02-09 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0044_bookingnotifications_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupportcollection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_customer_support_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
