# Generated by Django 3.2.15 on 2023-03-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodcontactinfo',
            name='do_parking_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodcontactinfo',
            name='do_you_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodcontactinfo',
            name='how_do_you_hear_about_us',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cleaner_notes',
            field=models.CharField(blank=True, default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_notes',
            field=models.CharField(blank=True, default='null', max_length=250),
        ),
    ]
