# Generated by Django 3.2.15 on 2023-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_auto_20230329_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='description',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
