# Generated by Django 3.2.15 on 2023-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_banners_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='service_image1'),
        ),
    ]
