# Generated by Django 3.2.15 on 2023-04-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_extra_image_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='image_1',
            new_name='image_12',
        ),
    ]
