# Generated by Django 3.2.15 on 2023-04-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_rename_image_1_extra_image_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_12pack',
            field=models.ImageField(blank=True, null=True, upload_to='service_image1'),
        ),
    ]
